name: Airflow CI/CD

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Lint DAG files
        run: |
          pylint .

  # deploy:
  #   name: Deploy DAGs to Airflow
  #   runs-on: ubuntu-latest
  #   needs: lint  # Only run deploy if lint job passes

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Deploy to Airflow server
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #       run: |
  #         ssh-agent bash -c "ssh-add - <<< \"$SSH_PRIVATE_KEY\"; rsync -avz --delete dags/ airflow@your_airflow_server:/path/to/airflow/dags"
