name: run test ssh remote script

on: workflow_dispatch


jobs: 
  deploy:
    name: Deploy DAGs to Airflow
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run script in Airflow server
        env:
          AIRFLOW_SSH_HOST: ${{ secrets.AIRFLOW_HOST }}
          AIRFLOW_SSH_USER: ${{ secrets.AIRFLOW_USER }}
          AIRFLOW_SSH_KEY: ${{ secrets.AIRFLOW_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AIRFLOW_SSH_KEY" >> ~/.ssh/id_rsa
          echo "Length of AIRFLOW_SSH_KEY: ${#AIRFLOW_SSH_KEY}"
          chmod 600 ~/.ssh/id_rsa
          # cat ~/.ssh/id_rsa
          ssh-keyscan -H 167.99.230.237 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa airflow@167.99.230.237 "echo 'Hello from GitHub Actions on the remote server!'"
